app/README.md
Just a tiny change, this way the command from the readme actually starts the electron app. Only showing a help on how to start it (which `npm run` does) is a bit confusing to me
=> 📝 App readme: start app with 'npm run start'

.pre-commit-config.yaml, app/src/components/TitleBar.tsx, app/src/start.ts, app/src/state/editor.ts
This will run `npm run format` during the pre-commit hook. If any files are changed, the hook will fail. However it will leave the changes the formatter produced in the file tree, so they can be easily commited.
=> 🔧 Run js formatter during pre-commit

app/src/state/editor.ts
From what I can tell the issue is that `mouseSelectionEnd` and `setTime` are both dispatched from the `click`-eventhandler. On my machine `setTime` is then processed after `mouseSelectionEnd`. So first `mouseSelectionEnd` sets the `state.mouseSelection` to `false`, which `setTime` checks and because of that it removes the selection.
I changed that by moving the selection reset to the `mouseSelectionStart` handler
=> 🐛 Race condition in selection onClick handlers

app/src/state/nav.ts
If the models were modified on the server while the app was running, we did not notice these updates
=> 🐛 Refresh models when opening transcribe screen

app/src/core/document.ts
The first element of a paragraph seems to sometimes have an "absoluteStart" set already, which seems to always be 0. This lead to some strange selection bugs, where some elements would be shown as selected without being in the selection and others not being shown as selected without being in the selection.
=> 🐛 Overwrite absoluteStart of items in computeTimed

app/src/pages/Editor/Paragraph.tsx, app/src/state/editor.ts
Right-clicking on a word places it in edit-mode, rightclicking again, clicking somewhere else, pressing enter, or otherwise losing focus moves it out of edit mode and saves the changes
I'm not sure what the proper UX for editing a word should be. I think right-clicking on a word in intuitive enough, but I'm not sure whether displaying a context menu with an "Edit word" option would be a better idea.
=> ✨ Allow editing of text

app/src/pages/Editor/Document.tsx, app/src/pages/Editor/SelectionMenu.tsx
This commits adds a resize listener on the window to recalculate the selection menu position. It also switches to absolute positioning, so the menu is in the correct position if we scroll the document.
Fixes #85
=> 🐛 Fix selection menu having wrong position on resize, scroll

.github/workflows/release.yml
Github changes something in the `macos-latest`-environment which broke our builds. This seems to fix it
=> 💚 Specify macos version

app/src/core/document.ts, app/src/util/itertools.spec.ts, app/src/util/itertools.ts
Previously we iterated through the entire document iterator on every render-frame, now we only stop once we found our items
=> ⚡️ Speedup cursor position calculation

.github/workflows/release.yml
v1 did not support multiple cache paths, which lead to it not caching anything at all
=> 🐛 Use actions/cache@v2 instead of v1

.github/workflows/release.yml
The ~/.cargo dir contains some more file cargo needs to properly run in the ci, else it will complain about pyoxidizer already being installed
=> 💚 Cache entire cargo dir in ci

app/electron-builder.config.js
We need ffmpeg-static to be unpacked, else the export breaks.
This PR fixes #165
=> 🐛 (app): Disable asar-packing in releases

app/src/pages/Editor/Cursor.tsx, app/src/pages/Editor/Document.tsx
we could additionally add binary search instead of linear search for finding the right item in the document for reducing the time-complexity from O(n) to O(log(n)) when going over word boundries but this already catches the low-hanging fruit of reducing the time complexity while staying in the same word to O(1).
=> speedup cursor position calculation with cache

app/src/core/document.ts, app/src/core/player.ts, app/src/pages/Editor/Cursor.tsx, app/src/pages/Editor/Document.tsx, app/src/pages/Editor/Player.tsx, app/src/pages/Editor/TitleBar.tsx, app/src/state/editor/edit.ts, app/src/state/editor/io.ts, app/src/state/editor/play.ts, app/src/state/editor/selection.ts, app/src/state/editor/types.ts, app/src/state/index.ts
this moves complexity into the player by giving it just the wanted state. this simplifies redux reducer code a lot.
=> ♻️ make player api declarative

app/src/core/document.ts, app/src/core/player.ts, app/src/pages/Editor/Cursor.tsx, app/src/pages/Editor/Document.tsx, app/src/state/editor/edit.spec.ts, app/src/state/editor/edit.ts, app/src/state/editor/index.ts, app/src/state/editor/io.ts, app/src/state/editor/play.ts, app/src/state/editor/selection.spec.ts, app/src/state/editor/selection.ts, app/src/state/util.ts
- 🧪️ add tests for editor.go{Left,Right}
- 🧪️ add tests for editor.selectionIncludeFully
- 🐛️ fix cursor cache invalidation
- 🐛️ prevent default actions on Arrow{Up,Down}
- 🐛️ fix handling of key-repeated delete
- 🐛️ fix playback on exportItem boundaries
- ♻️ change api for create{Async,}ActionWithReducer
- 🤯️ paste into current paragraph when same speaker
=> various editor improvements

.github/workflows/release.yml, app/package.json, app/scripts/generate_licenses.mjs
When setting up the repo in Windows, I ran into some initial problems.
commit#1 resolves the most important of those (`fmt`-script crashing), and should have no impact for Mac/Linux users. Please verify if you are unsure!
commit#2 is the result of running `prettier --write *` (ignoring .json, .md and extensionless files) in `/app`, which was required to avoid a heap of prettier-warnings. It just so happened that it caught some code not aligned with the prettier rules on the way.
I would suggest that moving forward, the `fmt`-script should also include `/ipc`, `/scripts` and all root-level `.js`-files to avoid similar issues/nuisances in the future. If you as maintainers agree, I can include that as a third commit in this same pull request.
=> 👷 Enable cross platform contributions

app/src/pages/Editor/ExportDocumentDialog.tsx
Until now, if an export crashed, it was no longer possible to export the file again.
=> 🐛 Handle export crashes

app/src/pages/Editor/Document.tsx
Previously it was hard to regain focus when the document lost it. This makes this easier (just click on the document)
=> 🖱️ set focus on mouse click to document

app/src/state/editor/selectors.spec.ts, app/src/state/editor/selectors.ts
Lodash's memoize only checks the first argument, which broke our selection
=> 🐛 Memoize on all function arguments

app/src/state/editor/selection.spec.ts, app/src/state/editor/selection.ts
If the selection head is on the left end of the document, we cannot move if further to the left. Same on the right end
Fixed #324
=> 🐛 Do not allow selection to be outside document

app/src/state/transcribe.ts
Fixes #327.
---
Untested, as you can probably guess from the `patch-1` branch name :sweat_smile: but it sure looks like this is the relevant code.
=> Add webm to importing extensions

README.md, app/electron-builder.config.js, app/get_version.js
=> 📦 Use + instead of - for versions

app/src/pages/LanguageSettings.tsx
This also includes a fix for a bug that cause the `ModelTable` to be re-rendered every time the model changed. During model download, this happened multiple times per second
=> 🚸 Improve "stop model download" ui

app/ipc/ipc_main.ts, app/ipc/ipc_renderer.ts
This fixes crashes when some log arguments were not serializable for IPC
=> 🐛 Run log arguments to string conversion before ipc

server/poetry.lock, server/pyproject.toml
This PR upgrades a bunch of dependencies, the most important one being Vosk, which now supports apple silicon. This means we can continue to work on #157 again
=> ⬆️ Upgrade python dependencies, enables m1 builds

app/src/core/document.ts, app/src/core/otio.ts, app/src/core/player.ts, app/src/pages/Editor/ExportOptions/Audio.tsx, app/src/pages/Editor/ExportOptions/Otio.tsx, app/src/pages/Editor/ExportOptions/Video.tsx, app/src/state/editor/selectors.spec.ts, app/src/state/editor/selectors.ts, app/src/state/editor/transcript_correction.ts
This PR ~removes the otio export, which doesn't work properly at the moment. This allows us to change~ **adds a flag to** the `renderItems` selector to ignore speaker changes and only care about source changes. Doing that results in less "crackling" during playback and in the exported files, which previously occured everytime the speaker changes.
=> Do not split render items on speaker change

.github/workflows/build.yml
set-output is deprecated https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> 💚 Remove set-output usage
