bugbakery/audapolis

LICENSE

Currently the license is only specified in the app/package.json. This PR adds a LICENSE-file for the whole repo, which will also include the server parts.

Add LICENSE file to repo

---

app/.eslintrc.json
app/.gitignore
app/package-lock.json
app/package.json
app/src/components/App.tsx
app/src/components/Controls.tsx
app/src/components/Landing.tsx
app/src/components/TitleBar.tsx
app/src/index.css
app/src/start.ts

* improve eslintrc and gitignore
* Add window with basic client sided decoration
* add landing page & button component

window frame & landing page

---

app/src/components/Editor.tsx

🐛 Styling for editor content

---

app/.eslintrc.json
app/package-lock.json
app/package.json
app/src/components/App.tsx
app/src/components/Editor.tsx
app/src/components/Landing.tsx
app/src/components/Transcribe.tsx
app/src/components/Transcribing.tsx
app/src/core/document.ts
app/src/core/webaudio.ts
app/src/start.ts
app/src/state/editor.ts
app/src/state/nav.ts
app/src/state/transcribe.ts
app/src/state/util.ts
server/README.md
server/app/main.py

Transcription UI

---

app/src/components/Editor.tsx
app/src/core/document.ts
app/src/core/webaudio.ts
app/src/exporters/ffmpeg.ts
app/src/state/editor.ts
server/app/transcribe.py

this makes a lot of computations more intuitive easier to understand.
closes #37.

refactor: store sourceStart + length

---

app/src/components/Transcribe.tsx
app/src/components/Transcribing.tsx

💄 Handle long file names in transcription screen

---

app/src/pages/Editor/Paragraph.tsx
app/src/state/editor.ts
app/src/util/index.ts
app/src/util/itertools.ts

If the user doubleclicks, select the clicked item. If they tripleclick, select the whole paragraph.

✨ Implement double & triple click selection

---

app/src/index.css

🐛 Show links in a lighter blue in dark mode

---

app/src/main_process/index.ts

Fixes #43 with the shortcut `ControlOrCommand+Alt+I`

🚸 Improve menu, add back shortcut for devtools

---

app/package-lock.json
app/package.json
app/src/custom.d.ts
app/src/exporters/ffmpeg.ts
app/src/main_process/index.ts
app/src/state/transcribe.ts
server/app/main.py
server/app/transcribe.py

This removed the ffmpeg dependency in the server component and fixes #47

✨ Include ffmpeg in app, only send wav to backend

---

app/package-lock.json

I deleted the package-lock.json and reran `npm install`. Don't ask me why but not the build works (https://github.com/audapolis/audapolis/actions/runs/1305738837).
@anuejn do you have an idea for a cleaner solution?

💚 Fix ci build with new package-lock.json

---

app/package-lock.json
app/package.json

This should fix the build on mac os

Fix mac build

---

.github/workflows/release.yml

👷 Run electron build for each PR

---

app/src/state/transcribe.ts

🐛 Show "transcription" screen *before* wav-conversion

---

app/src/state/transcribe.ts
server/app/main.py
server/app/tasks.py

✨ Delete transcription tasks after the app no longer needs them

---

app/src/state/editor.ts

🩹 Allow undoing pastes

---

app/package-lock.json
app/package.json
app/src/core/player.ts
app/src/exporters/ffmpeg.ts
app/src/types/appdirectiory.d.ts
server/app/config.py
server/app/main.py
server/app/models.py

- :truck: store temporary files in user cache dir
- 🎞️  better video export

🎞️  better video export

---

app/src/state/editor.ts

🐛 Fix curosr bug when clicking while playing

---

app/package-lock.json
app/package.json
app/src/components/App.tsx
app/src/components/Controls.tsx
app/src/components/FilePicker.tsx
app/src/components/Util.tsx
app/src/core/document.spec.ts
app/src/core/document.ts
app/src/core/ffmpeg.ts
app/src/core/otio.ts
app/src/core/player.ts
app/src/index.tsx
app/src/main_process/index.ts
app/src/pages/Editor/ExportDocumentPopup.tsx
app/src/pages/Editor/TitleBar.tsx
app/src/pages/Editor/index.tsx
app/src/pages/Transcribe.tsx
app/src/state/editor.ts
app/src/state/transcribe.ts
app/src/util/index.ts
server/app/main.py
server/app/otio.py
server/poetry.lock
server/pyproject.toml
server/shell.nix

- 💽️ store temporary files in user cache dir
- 🎞️  better video export
- 🚛️ add OpenTimelineIO based export

OpenTimelineIO based export

---

app/src/pages/Transcribe.tsx
app/src/state/transcribe.ts
server/app/main.py
server/app/transcribe.py
server/poetry.lock
server/pyproject.toml
server/scripts/transcribe.py

✨ Diarization

---

.github/workflows/release.yml
app/electron-builder.config.js
app/package.json

💚 Build for more archs & formats (M1, deb, rpm, snap, pacman)

---

.github/workflows/import_cert.sh
.github/workflows/release.yml

This is required for apps to start at all on apple silicon

💚 (app): Sign mac builds

---

app/src/pages/Editor/SelectionMenu.tsx
app/src/state/editor.ts

✨ Add button so copy selection as text

---

.github/workflows/release.yml
.pre-commit-config.yaml
app/package.json

- 😅️ rename npm scripts to match cargo
- 🚲️🛖️ rename build step in ci

bikeshed naming

---

app/src/state/transcribe.ts

🩹 Allow more extensions when importing

---

app/src/core/otio.ts
app/src/server_api/api.ts
app/src/server_api/index.ts
app/src/state/models.ts
app/src/state/server.ts
app/src/state/transcribe.ts
app/src/util/index.ts

this allows for better typing thus catching bugs earlier

🌳️ refactor: centralize server api usage

---

app/jest.config.js
app/src/core/document.spec.ts
app/src/core/document.ts
app/src/pages/Editor/Cursor.tsx
app/src/state/editor/play.spec.ts
app/src/state/editor/play.ts
app/src/util/itertools.spec.ts
app/src/util/itertools.ts

- ♻️ make player api declarative
- 🧪️ add test for editor/goLeft
- 🐛️ fix cursor not being re-positioned
- 🐛️ fix itertools.dropwhile
- 🐛️ fix cursor left / right movement
- 🧪️ add tests for cursor left / right movement

fix cursor movement

---

server/app/transcribe.py
server/poetry.lock
server/pyproject.toml

✨ Make transcription multi-threaded

---

app/src/core/ffmpeg.ts
app/src/pages/Editor/ExportDocumentDialog.tsx
app/src/pages/Editor/ExportOptions/Audio.tsx
app/src/pages/Editor/ExportOptions/Otio.tsx
app/src/pages/Editor/ExportOptions/Subtitles.tsx
app/src/pages/Editor/ExportOptions/Video.tsx
app/src/pages/Editor/ExportOptions/index.ts
app/src/pages/Editor/TitleBar.tsx
app/src/pages/Transcribing.tsx
app/src/server_api/api.ts
app/src/state/editor/io.ts
app/src/state/editor/types.ts
app/src/state/models.ts
app/src/state/transcribe.ts
server/app/models.py
server/app/transcribe.py

- calculate task progress in backend
- show progress of conversion to wav

Progress updates

---

app/ipc/ipc_main.ts
app/ipc/ipc_renderer.ts
app/main_process/menu.ts
app/src/components/TitleBar.tsx
app/src/components/menu.ts
app/src/state/editor/io.ts

half of the refactor was eaten by a rebase. this adds the missig parts back in

🙈️ fix ipc refactor

---

app/src/state/editor/display.ts
app/src/state/transcribe.ts

✨ Always show speakers after import if diarization is on

---

app/src/pages/Editor/Document.tsx

✨ Better selection

---

server/pyoxidizer.bzl

💚 Fix missing libblas on linux

---

app/src/pages/Transcribe.tsx
app/src/server_api/api.ts
app/src/state/transcribe.ts
server/app/main.py
server/app/transcribe.py

✨ 3-way switch for diarization

---

app/ipc/ipc_main.ts
app/src/core/document.ts
app/src/pages/Editor/ExportDocumentDialog.tsx
app/src/state/editor/io.ts
app/src/state/transcribe.ts
app/src/state/util.ts

- 🙈️ fix rejected in createAsyncThunkWithReducers
- 💽️ correctly handle disk full

💽️ correctly handle disk full

---

app/main_process/server.ts

It cannot find poetry otherwise and the server does not start (ENOENT)

🧑‍💻 Run poetry with shell on windows

---

.github/workflows/release.yml
app/electron-builder.config.js
app/get_version.js
app/ipc/ipc_main.ts

now the package version + the number of commits since the last bump is used as a version

🏛️ improve in-app versioning

---

app/src/core/webvtt.ts
app/src/pages/Editor/Document.tsx
app/src/pages/Editor/Paragraph.tsx
app/src/state/editor/edit.ts
app/src/state/editor/selectors.spec.ts
app/src/state/editor/selectors.ts

- ☝️ better handling of null speakers
- 🐛️ fix handling of null speakers in colorization
- Revert "🐛️ fix handling of null speakers in colorization"
- 🖥️ display placeholder if speaker is not set

☝️ better handling of null speakers

---

app/src/pages/Editor/ExportDocumentDialog.tsx
app/src/pages/Editor/SelectionMenu.tsx
app/src/pages/Editor/TitleBar.tsx
app/src/state/editor/display.ts
app/src/state/editor/edit.ts
app/src/state/editor/io.ts
app/src/state/editor/selectors.spec.ts
app/src/state/editor/selectors.ts
app/src/state/editor/types.ts

This adds the capability to export sections as video, subtitles or otio

📽️ use normal export dialog for selectio export

---

app/src/pages/Editor/ExportDocumentDialog.tsx

🐛 Fix crash if "Esc" after interacting with export dialog

---

app/electron-builder.config.js
app/main_process/index.ts
app/package-lock.json
app/package.json

We need to build zips for mac os to support auto-updates.
**Point of discussion**: This just silently auto-updates the app,  so the new version will start once the app is re-started. It will also show a notification on supported systems. Is this what we want or do we want to ask the users before downloading and installing a new version?

✨ Auto-Updates

---

app/src/state/editor/selectors.spec.ts
app/src/state/editor/selectors.ts

🐛 Correctly calculate time after last element

---

app/get_version.js

Damn you electron builder or github or whoever is responsible for not allowing + in filesnames

💚 Version with . instead of +

---

app/src/state/editor/io.ts

🐛 Fix undo working across documents

---

app/package-lock.json

This should also upgrade some third-party libraries which github dependency alerts keeps bugging me about

⬆️ Upgrade evergreen version

---

app/src/pages/Editor/Filter/index.tsx
app/src/pages/Editor/MenuBar.tsx
app/src/pages/Editor/index.tsx
app/src/state/editor/display.ts
app/src/state/editor/edit.spec.ts
app/src/state/editor/edit.ts
app/src/state/editor/index.ts
app/src/state/editor/types.ts

With this you can create videogrep-style supercuts. Closes #365.
This PR is based on #354, so let's maybe merge that one first

✨ Add document filter action

---

server/build_server.sh

Fixes build failure https://github.com/python-poetry/poetry/issues/6275

🚑️ Use poetry export -o instead of shell redirect

---

app/package-lock.json
app/package.json
app/src/core/webvtt.spec.ts

⬆️ Bump webvtt-writer

---

app/main_process/menu.ts

🚸 Add shortcuts for zooming in/out

---

server/build_server.sh

realpath doesnt exist on the github runners

🏗️ Replace realpath with readlink -f
